apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-vulnerable
  labels:
    app: vulnerable-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-app
  template:
    metadata:
      labels:
        app: vulnerable-app
    spec:
      containers:
      - name: vulnerable-container
        image: imagen_vulnerable
        ports:
        - containerPort: 80
