apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerables-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerables
  template:
    metadata:
      labels:
        app: vulnerables
    spec:
      containers:
        - name: vulnerables
          image: imagen_vulnerable
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
